### ISSUE TITLE
Import issues in "predict_multi_scene_t2v_mask2dit.py"

### ISSUE THREAD

**Issue by XqZeppelinhead0702** [Tianhao-Qi/Mask2DiT#3]
Hi, really appreciate your effort to open source your marvellous work. However, there seems to be some import issues in your code. For example, in the following lines of "predict_multi_scene_t2v_mask2dit.py":
```python
import os
import sys
import json
import argparse
import numpy as np
import torch

from diffusers import (CogVideoXDDIMScheduler, DDIMScheduler,
                       DPMSolverMultistepScheduler,
                       EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
                       PNDMScheduler)
from PIL import Image
from transformers import T5EncoderModel
...
from videox_fun.models import (AutoencoderKLCogVideoX,
                              MultiPromptCogVideoXTransformer3DModel, T5EncoderModel,
                              T5Tokenizer)
from videox_fun.pipeline import (MultiPromptCogVideoXFunPipeline,
                                CogVideoXFunInpaintPipeline)
from videox_fun.utils.fp8_optimization import (convert_model_weight_to_float8, replace_parameters_by_name,
                                              convert_weight_dtype_wrapper)
from videox_fun.utils.lora_utils import merge_lora, unmerge_lora
from videox_fun.utils.utils import get_image_to_video_latent, save_videos_grid
from videox_fun.dist import set_multi_gpus_devices, shard_model
...
```
In fact, it can not import modules like AutoencoderKLCogVideoX directly from models.py in videox_fun because there isn't a "__init__.py" to include classes or functions from sub-modules (e.g. cogvideox_vae.py) of "videox_fun.models" that enable these modules directly imported from "videox_fun.models". 

Moreover, I failed to find "T5EncoderModel" and "T5Tokenizer" and I wonder where these two modules come from. Given that you also write "from transformers import T5EncoderModel", it makes me more confused about this question. 

Could you give me some guidance to solve these import issues? Thanks!

**Comment by Tianhao-Qi** [comment]
@XqZeppelinhead0702 Thanks a lot for catching this — you’re absolutely right.

Root cause: my .gitignore had a pattern like \_* which unintentionally ignored all \_\_init_\_.py files (since \_\_init\_\_.py starts with _).

I’ve now pushed all missing \_\_init\_\_.py files. Could you please pull the latest version and retry?

**Comment by XqZeppelinhead0702** [comment]
@Tianhao-Qi Thanks for your timely response. I've tried the newly updated version but still encounter some import issues in "videox_fun.dist" which cause errors to "videox_fun/models/cogvideox_transformer3d.py":
```python
...
from ..dist import (get_sequence_parallel_rank,
                    get_sequence_parallel_world_size, 
                    get_sp_group,
                    xFuserLongContextAttention)
...
```
Seems like "videox_fun.dist" also needs a corresponding "__init__.py" file:)

**Comment by Tianhao-Qi** [comment]
@XqZeppelinhead0702 Done.

**Comment by XqZeppelinhead0702** [comment]
@Tianhao-Qi Retry and work fine. Since the program is still running, I’ll keep the issue open for now and close it once the results are confirmed to be normal :) Really thanks and have a good night!😀
